### PR TITLE
Sepal tests

### PR DESCRIPTION
**Pull request by Innectic**
## What does this change?
Adds sepal tests.
## Requirements

 - [x] Only PG-rated language used (code, commits, etc.)
 - [x] Descriptive commit messages
 - [x] Changes have been tested
 - [x] Changes do not break any existing functionalities

### CODE REVIEW

**Comment by 2Cubed** [comment]
@Innectic Looks like you're going to want to pass `[CONFIG_PACKET]`, as it's looking for a list. https://github.com/CactusDev/CactusBot/blob/develop/cactusbot/sepal.py#L81

**Comment by Innectic** [comment]
@2Cubed I don't think so. That just makes it error more, because the actual parser method isn't looking for that

**Comment by 2Cubed** [comment]
@Innectic Oh, derp, right, sorry. Missed what it was iterating over.

**Comment by 2Cubed** [comment]
**Note: This has not been integration-tested!** We currently have no confirmation that the packets work in a production environment. (Need Sepal config packet sending to be fixed first. cc: @Innectic)

**Review by 2Cubed — APPROVED** [review]

**Pull request merged**
